### PR TITLE
Change Web Hosting Dir Path for Python Server

### PR DESCRIPTION
**Pull request by beerMT**
When working with the project, my team asked if I could get the python server to host the editor page ($ python dettect.py editor) without having to click through the landing page (hyperlink shows as dettect-editor) on localhost:8080. This is especially useful when hosting behind a reverse proxy like Nginx.

Wanted to offer this up to see if it makes a small improvement on user workflow. Cheers! Thanks for a great project and thanks for keeping data sources relevant with Att&ck v9 progress.

### CODE REVIEW

**Comment by marcusbakker** [comment]
Hi Brad,

If I understand you correctly, you're hosting the Editor on a web server and not using it by launching it via the CLI or going to this [page](https://rabobank-cdc.github.io/dettect-editor)?

Regards,
Marcus

**Comment by beerMT** [comment]
Hi Marcus,

I think we are on the same page with use case. The Editor is hosted on a web server and will have the latest yaml file mapped to it that will be available to internal sec team.

Regardless of if the user is hosting it in this fashion or launching the server from CLI ($ python dettect.py editor), the change should simplify the URL path for browser navigation.

Current URL to view editor: localhost:8080/dettect-editor/#/home or https://yourPath:8080/dettect-editor/#/home 

Proposed URL to view editor: local:8080 or https://yourPath:8080

The proposed is achieved by modifying where the python server is hosting the web directory path from, as well as changing a few resource paths in the index.html.

If this doesn't solve a problem, feel free to discard.

Cheers,
Brad

**Comment by marcusbakker** [comment]
Hi Brad,

Thanks for the extra info.

I've slightly modified your proposed change to make sure any new build (using `npm`) has this new path and prevent breaking the Editor hosted version on GitHub pages. It's already live via the latest two commits.

Marcus

**Comment by beerMT** [comment]
Update works slick, thanks for knocking that out!

**Comment by marcusbakker** [comment]
Good to hear that Brad!

**Pull request closed without merging**
